# Move this file to: `~/.amethyst.yml`
# In order to register changes restart Amethyst.
# If you experience issues pulling in the changes you can also quit Amethyst and run: `defaults delete com.amethyst.Amethyst.plist`
# This removes the current preferences and causes Amethyst to restart with default preferences and pull configs from this file.

layouts:
  - floating
  - fullscreen
  - tall
mod1:
  - option
  - command
mod2:
  - option
  - shift
  - command
mod3:
  - shift
  - command
display-current-layout:
  mod: mod3
  key: i
swap-screen-ccw:
  mod: mod3
  key: h
swap-screen-cw:
  mod: mod3
  key: l
swap-ccw:
  mod: mod3
  key: j
swap-cw:
  mod: mod3
  key: k
mouse-follows-focus: false
mouse-swaps-windows: true
mouse-resizes-windows: true
focus-follows-mouse: false
new-windows-to-main: true
