#!/bin/sh

# Activate using:
# sudo chmod +rx wififix
# sudo cp wififix /lib/systemd/system-sleep/

# Also, ensure resolved has the right systemd config
# sudo ln -fs /run/systemd/resolve/resolv.conf /etc/resolv.conf

set -e

if [ "$2" = "suspend" ] || [ "$2" = "hybrid-sleep" ]; then
    case "$1" in
        pre) true ;;
        post) sleep 1 && service resolveconf restart && service network-manager restart  ;;
    esac
fi
