{:user {:plugins [[lein-ancient "0.6.7"]
                  [lein-exec "0.3.5"]
                  [lein-pprint "1.1.2"]
                  [lein-try "0.4.3"]
                  [refactor-nrepl "1.2.0-SNAPSHOT"]
                  [cider/cider-nrepl "0.10.0-SNAPSHOT"]
                  [http-kit/lein-template "1.0.0-SNAPSHOT"]
                  [compojure-app/lein-template "0.4.7"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.10"]
                       [compliment "0.2.5"]]}}
