#!/bin/bash
set -xeuo pipefail

sudo pamac upgrade -a

# Install (most) programs.
sudo pamac install --no-confirm \
    base-devel kitty xkbset xclip starship rlwrap git-delta net-tools dnsutils \
    editorconfig-core-c-git tofrodos aspell pass pv lsof dsh mise imagemagick \
    pasystray xfce4-volumed-pulse xfce4-screensaver xscreensaver-backends \
    feh flameshot arc-gtk-theme gtk-chtheme lxappearance redshift noto-fonts-emoji \
    transmission-gtk transmission-cli edk2-ovmf dnsmasq baobab-gtk3 \
    # needed for dbus sbcl package
    clj-kondo-bin clojure-lsp-bin ghcup-hs-bin insomnia-bin libfixposix \
    multimarkdown cowsay cmatrix gnuchess pychess stockfish

sudo pamac remove light-locker thunderbird
sudo ln -s /usr/lib/xfce4/notifyd/xfce4-notifyd /usr/bin/xfce4-notifyd
sudo ln -s /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 /usr/bin/polkit-agent
sudo cp ./desktop/xmatrix.desktop /usr/share/applications/screensavers/

# Install oh-my-zsh and set as default.
RUNZSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/zdharma-continuum/history-search-multi-word.git $HOME/.oh-my-zsh/custom/plugins/history-search-multi-word --depth 1

# Copy dotfiles.
rsync -av --progress . $HOME \
      --exclude .git \
      --exclude .gitmodules \
      --exclude README.md \
      --exclude desktop \
      --exclude scripts

# Create $HOME/projects directory.
if [ ! -d $HOME/projects ]; then
    mkdir $HOME/projects
fi

# Create $HOME/.local/bin directory.
if [ ! -d $HOME/.local/bin ]; then
    mkdir $HOME/.local/bin
fi

# Install tools through mise.
mise install

./scripts/emacs
./scripts/stumpwm
./scripts/node-modules
./scripts/pcloud
./scripts/lima
./scripts/pia
./scripts/stack-deps
